### ISSUE TITLE
Add support of vue-property-decorator

### ISSUE THREAD

**Issue by BigForNothing** [vue-styleguidist/vue-docgen-api#9] opened 2017-10-26 18:08 UTC
> Cannot parse src\components\example\example.vue: Error: SyntaxError: unknown: Unexpected token (17:0)

The line in question is the ```@Component``` from vue-component-class/vue-property-decorator. 

I've setup the styleguide.config.js to point to the appropriate webpack config as well.

**Comment by znck** [comment] 2017-11-15 17:45
This would be resolved easier if you go with #11

**Comment by wadetandy** [comment] 2018-02-26 22:22
Any word on this work?  We are an all-typescript shop and I think styleguidist would be a fantastic tool for us, but are currently blocked from trying it out.  Any help you can provide here would be appreciated!

**Comment by rafaesc** [comment] 2018-02-26 22:54
Hi @wadetandy,

Yes, I had tried to implement https://github.com/jackmellis/require-extension-hooks-vue

But it doesn't support typescript
https://github.com/jackmellis/require-extension-hooks-vue/issues/23

So I have thought that the solution is to creates another repository like this
https://github.com/styleguidist/react-docgen-typescript

In this time I don't have too much time to create this repository, so it's probably that I will do it in the next months.

However, if you want to do it, you can tell me so I can help you.

Regards

**Comment by wadetandy** [comment] 2018-02-27 16:47
@rafaesc So I haven't done a deep dive into this codebase yet, but it looks like all of the parsing work being done is here: https://github.com/vue-styleguidist/vue-docgen-api/blob/master/src/utils/getSandbox.js#L110-L111

Is there any reason it wouldn't work to sub in different parse function for typescript?

**Comment by rafaesc** [comment] 2018-02-27 17:10
Hi @wadetandy,

yes, the problem it's that typescript has another syntax, so it isn't possible to use `getParseBabel`.

So it's necessary to develop a way to import the object with vue configuration component with typescript, maybe convert from `ts` to `js`, or create a channel to import this files, another parser like `getParselBabel` but for typescript.

https://github.com/vue-styleguidist/vue-docgen-api/blob/master/src/utils/getParseBabel.js

**Comment by rafaesc** [comment] 2018-03-09 17:08
Thanks to @wadetandy,

there is a typescript support, on 2.3.0 version.

it's necessary to install the library typescript

`npm install typescript --save`

However also should support the library [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator) because [vue-cli-plugin-typescript](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-typescript) support that. [case](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-typescript/generator/template/src/components/HelloWorld.vue)

For that, I created the branch [ts-support](https://github.com/vue-styleguidist/vue-docgen-api/tree/ts-support), and I will work in that.

Thanks to everybody

**Comment by rothsandro** [comment] 2018-09-13 15:47
Any update on this?

**Comment by JessicaSachs** [comment] 2019-01-19 14:03
@Component is not typescript. @Component is a decorator. Decorators are being proposed in TC39 for Javascript and have babel support.

Here is an example `babel.config.js` which allows for TC39 Decorators and @Component notation. vue-docgen-api should use the existing babel configuration when parsing source...

```
module.exports = {
    presets: [['@babel/env']],
    plugins: [
        ['@babel/plugin-proposal-decorators', { legacy: true }],
        ['@babel/plugin-proposal-class-properties', { loose: true }],
    ],
    sourceType: 'unambiguous',
};
```

**Comment by elevatebart** [comment] 2019-01-19 20:36
@JessicaSachs, I absolutely agree. decorators are not specific to TypeScript.
The PR #68 is taking this into account. The new code i parsing all files regardless of their language only difference being:
- If the component js babel is assigned a `flow` plugin for the case if you guys are using `flow`. 
- if the file is TypeScript I add the typescript plugin to be able to deduce types from the type specifiers.

@rafaesc and I  meet tomorow. hopefully we will deliver then ;)

**Comment by JessicaSachs** [comment] 2019-01-21 04:06
Here's [an example repository](https://github.com/jessicasachs/design-sys) that isn't working that I believe should be. I downloaded the latest 3.0.0 release for vue-docgen-api when testing this.

Steps to reproduce:
1. Clone the repo
2. `npm i`
3. `npm run styleguide`
4. Observe the console's errors
5. When you open the styleguidist server, none of the components using vue-property-decorator are there.

The error message that occurs is when it attempts to parse `src/HelloWorld.vue` (the first component with vue-property-decorator usage)

Here are the error messages I get:

```
Loading webpack config from:
/Users/jessicasachs/projects/design-sys/node_modules/@vue/cli-service/webpack.config.js

You can now view your style guide in the browser:

  Local:            http://localhost:6060/
  On your network:  http://192.168.1.75:6060/

Warning: Cannot parse src/components/AppButton.vue: TypeError: (0 , _vuePropertyDecorator.Component) is not a function

It usually means that vue-docgen-api does not understand your source code or when using third-party libraries, try to file an issue here:
https://github.com/vue-styleguidist/vue-docgen-api/issues

Warning: Cannot parse src/components/HelloWorld.vue: TypeError: (0 , _vuePropertyDecorator.Prop) is not a function

It usually means that vue-docgen-api does not understand your source code or when using third-party libraries, try to file an issue here:
https://github.com/vue-styleguidist/vue-docgen-api/issues

 DONE  Compiled successfully!
```

**Comment by JessicaSachs** [comment] 2019-01-21 13:12
1. Hm, when I do `npm list --depth=0 | grep docgen`, the only dependency installed is docgen v 3.0.0... Can you explain how to install the right version? I don't see that version on the Tags or the Releases page.
2. That's totally fine! I've changed my code to do this. I still get the errors with (what I believe is v 3.0.0) of the plugin?

**Comment by elevatebart** [comment] 2019-01-21 13:22
Just created a PR on your repo, to illustrate what I was saying.
I will try to sort out the issue of indirect exporting ASAP.
JessicaSachs/design-sys#1

**Comment by elevatebart** [comment] 2019-01-21 14:42
I think support has been added, closing this issue. 
If support is buggy, please open a new one with the bug you encountered

Thank you all

**Closed by elevatebart** 2019-01-21 14:42 UTC
Labels: AST, help wanted

**Comment by JessicaSachs** [comment] 2019-01-21 16:14
I spoke a bit too soon. I tried adopting it on my production codebase and found that adding any "data" properties causes vue-docgen-api to blow up. Here's the separate issue. https://github.com/vue-styleguidist/vue-docgen-api/issues/76
